shopping :-
    Nomes = ['Adams', 'Baker', 'Catt', 'Dodge', 'Ennis', 'Fisk'],
    Andares = [A1, A21, A22, A3, A5, A6],
    Produtos = [Livro, Vestido, Bolsa, Gravata, Chapeu, Candeeiro],
    domain(Produtos, 0, 5),
    all_distinct(Produtos),
    Adams = 0,
    Baker = 1,
    Catt = 2,
    Dodge = 3,
    Ennis = 4,
    Fisk = 5,
    A1 #= Adams,
    A21 #= Catt,
    A22 #= Gravata,
    A3 #= Vestido,
    A5 #= Candeeiro,
    A6 #= Fisk,
    Baker #\= Bolsa,
    Baker #\= Gravata,
    A21 #= Bolsa,
    A1 #= Livro,
    A5 #= Ennis,
    labeling([], Produtos),
    nth0(Livro, Nomes, NomeLivro),
    nth0(Vestido, Nomes, NomeVestido),
    nth0(Bolsa, Nomes, NomeBolsa),
    nth0(Gravata, Nomes, NomeGravata),
    nth0(Chapeu, Nomes, NomeChapeu),
    nth0(Candeeiro, Nomes, NomeCandeeiro),
    write(NomeLivro),
    write(': Livro'),
    nl,
    write(NomeVestido),
    write(': Vestido'),
    nl,
    write(NomeBolsa),
    write(': Bolsa'),
    nl,
    write(NomeGravata),
    write(': Gravata'),
    nl,
    write(NomeChapeu),
    write(': Chapeu'),
    nl,
    write(NomeCandeeiro),
    write(': Candeeiro').