:- use_module(library(clpfd)).

restaurant :-
    Names = ['Bernard', 'Daniel', 'Francisco', 'Henrique', 'Jaqueline', 'Luis'],
    People = [Bernard, Daniel, Francisco, Henrique, Jaqueline, Luis],
    Dishes = [Peixe, Porco, PatoLaranja, Omelete, Bife, Esparguete],
    all_distinct(People),
    all_distinct(Dishes),
    domain(People, 0, 5),
    domain(Dishes, 0, 5),
    Daniel #\= Peixe,
    Jaqueline #\= Peixe,
    Francisco #\= Porco,
    Francisco #\= PatoLaranja,
    Bernard #\= Omelete,
    Bernard #\= PatoLaranja,
    Daniel #\= Omelete,
    Daniel #\= PatoLaranja,
    Bernard #\= Peixe,
    Bernard #\= Esparguete,
    Francisco #\= Peixe,
    Francisco #\= Omelete,
    Francisco #\= Esparguete,
    Henrique #\= Peixe,
    Henrique #\= Omelete,
    Henrique #\= Esparguete,
    labeling([], Dishes),
    nth0(Bife, Names, NameBife),
    nth0(Esparguete, Names, NameEsparguete),
    write(NameBife),
    nl,
    write(NameEsparguete).